uaDom = {
	"title":"хрестики - нуліки",
	"#reset-game":{ value:"Вибрати гравців" },
	"#start-game":{ value:"Почати гру" },
	"#player-1 > span":"Гравець X",
	"#player-2 > span":"Гравець O",
	"#player-1-human":"Людина",
	"#player-1-bot1":"Новачок",
	"#player-1-bot2": "Юніор",
	"#player-1-bot3":"Експерт",
	"#player-1-score":"Рахунок (X): ",
	"#player-2-human":"Людина",
	"#player-2-bot1":"Новачок",
	"#player-2-bot2": "Юніор",
	"#player-2-bot3":"Експерт",
	"#player-2-score":"Рахунок (O): ",
	"#games-count":"Ігор зіграно: ",
	".draw":"НІЧИЯ!",
	".waiting":"Гей, Людина, твій Хід!",
	".player-1":"Переміг (X) !",
	".player-2":"Переміг (O) !",
};
