ruDom = {
	"title":"крестики - нолики",
	"#reset-game":{ value:"Выбрать игроков" },
	"#start-game":{ value:"Начать игру" },
	"#player-1 > span":"Игрок X",
	"#player-2 > span":"Игрок O",
	"#player-1-human":"Человек",
	"#player-1-bot1":"Новичок",
	"#player-1-bot2":"Юниор",
	"#player-1-bot3":"Эксперт",
	"#player-1-score":"Счёт (X):  ",
	"#player-2-human":"Человек",
	"#player-2-bot1":"Новичок",
	"#player-2-bot2":"Юниор",
	"#player-2-bot3":"Эксперт",
	"#player-2-score":"Счёт (O):  ",
	"#games-count":"Игр сыграно:  ",
	".draw":"НИЧЬЯ !",
	".waiting":"Эй, Человек, Твой Ход!",
	".player-1":"Победил (X) !",
	".player-2":"Победил (O) !",
};
